# Generated by Django 3.1.2 on 2020-10-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentmodel',
            options={'verbose_name': 'родителя', 'verbose_name_plural': 'родители'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='user',
            name='third_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Аккаунт подтвержден'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='Телефон'),
        ),
    ]
