# Generated by Django 3.1.2 on 2020-10-12 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201012_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Родитель'),
        ),
        migrations.DeleteModel(
            name='ParentModel',
        ),
    ]
