version: '3.8'
services:
  app:
    build: .
    restart: always
    command: sh -c "python manage.py migrate && gunicorn -b 0.0.0.0:8000 -w 2 school.wsgi --log-file -"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    volumes:
      - ./pg_data:/var/lib/postgresql