# Generated by Django 3.1.2 on 2020-10-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_auto_20201009_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Текст')),
                ('publish_date', models.DateTimeField(verbose_name='Дата и время публикации')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('thumbnail', models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Изображение совета')),
            ],
            options={
                'verbose_name': 'совет',
                'verbose_name_plural': 'советы',
                'db_table': 'advices',
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('publish_date', models.DateTimeField(verbose_name='Дата и время публикации')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('thumbnail', models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Изображение новости')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Навзвание филиала')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'филиал',
                'verbose_name_plural': 'филиалы',
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'дисциплина',
                'verbose_name_plural': 'дисциплины',
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('job', models.CharField(max_length=250, verbose_name='Должность')),
                ('experience', models.TextField(verbose_name='Стаж')),
                ('education', models.TextField(verbose_name='Образование')),
                ('photo', models.ImageField(upload_to='teachers/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='TextbookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(upload_to='textbooks/%Y/%m/%d/', verbose_name='Файл пособия')),
            ],
            options={
                'verbose_name': 'пособие',
                'verbose_name_plural': 'пособия',
                'db_table': 'textbooks',
            },
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('finish_date', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('students', models.ManyToManyField(to='account.StudentModel', verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'мероприятия',
                'db_table': 'events',
            },
        ),
    ]
