# Generated by Django 3.1.2 on 2020-10-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_schedulemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textbookmodel',
            options={'verbose_name': 'учебное пособие', 'verbose_name_plural': 'учебные пособия'},
        ),
    ]
