# Generated by Django 3.1.1 on 2020-09-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200922_2137'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='verificationmodel',
            table='verification',
        ),
    ]
