# Generated by Django 3.1.2 on 2020-10-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201012_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='third_name',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Отчество'),
        ),
    ]
