# Generated by Django 3.1.2 on 2020-10-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20201012_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='phone',
            field=models.CharField(max_length=11, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='third_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='year_of_study',
            field=models.IntegerField(choices=[(1, 'Первый'), (2, 'Второй'), (3, 'Третий'), (4, 'Четвертый'), (5, 'Пятый'), (6, 'Шестой'), (7, 'Седьмой'), (8, 'Восьмой'), (9, 'Девятый'), (10, 'Десятый'), (11, 'Одиннадцатый')], verbose_name='Класс'),
        ),
    ]
