# Generated by Django 3.1.3 on 2020-11-22 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20201015_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'класс',
                'verbose_name_plural': 'класса',
                'db_table': 'grades',
            },
        ),
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'verbose_name': 'отзыва', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='year_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.grademodel', verbose_name='Класс'),
        ),
    ]
