# Generated by Django 3.1.4 on 2020-12-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20201122_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grademodel',
            options={'verbose_name': 'класс', 'verbose_name_plural': 'классы'},
        ),
    ]
