# Generated by Django 3.1.3 on 2020-11-22 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20201122_2037'),
        ('home', '0003_auto_20201012_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemodel',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.schoolmodel', verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teachermodel', verbose_name='Преподаватель'),
        ),
        migrations.CreateModel(
            name='StudyGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('classes', models.ManyToManyField(to='account.GradeModel', verbose_name='Классы')),
            ],
            options={
                'verbose_name': 'учебная группа',
                'verbose_name_plural': 'учебной группы',
                'db_table': 'study_groups',
            },
        ),
        migrations.AddField(
            model_name='schedulemodel',
            name='study_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.studygroupmodel', verbose_name='Учебная группа'),
        ),
    ]
