# Generated by Django 3.1.4 on 2020-12-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201122_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studygroupmodel',
            options={'verbose_name': 'учебную группу', 'verbose_name_plural': 'учебные группы'},
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='weekday',
            field=models.CharField(choices=[('0', 'понедельник'), ('1', 'вторник'), ('2', 'среда'), ('3', 'четверг'), ('4', 'пятница'), ('5', 'суббота'), ('6', 'воскресенье')], max_length=1, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
