# Generated by Django 3.1.4 on 2020-12-17 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20201122_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermodel',
            name='name',
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
