# Generated by Django 3.1.3 on 2020-12-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201202_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='sex',
            field=models.CharField(choices=[('f', 'Жен.'), ('m', 'Муж.')], default='f', max_length=1, verbose_name='Пол'),
        ),
    ]
