# Generated by Django 3.1.4 on 2020-12-17 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_auto_20201217_1439'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название комнаты')),
                ('slug', models.SlugField(unique=True, verbose_name='Ярлык комнаты')),
                ('start_date', models.DateTimeField(verbose_name='Время старта')),
                ('finish_date', models.DateTimeField(verbose_name='Время окончания')),
                ('speakers', models.ManyToManyField(to='home.TeacherModel', verbose_name='Докладчики')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'комнаты',
                'verbose_name_plural': 'комнаты',
                'db_table': 'room',
            },
        ),
    ]
