# Generated by Django 3.1.4 on 2020-12-17 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201217_1756'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='speakers',
            field=models.ManyToManyField(related_name='speaker', to='home.TeacherModel', verbose_name='Докладчики'),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='users',
            field=models.ManyToManyField(related_name='visitor', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
